// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// In-process lock replaces navigator.locks to avoid contention during OAuth
// redirects (Lovable cloud-auth init + Supabase _initialize both race for the
// same lock, causing a timeout that drops the session).
const inProcessLocks = new Map<string, Promise<unknown>>();

async function processLock<R>(
  name: string,
  _acquireTimeout: number,
  fn: () => Promise<R>,
): Promise<R> {
  const prev = inProcessLocks.get(name);
  if (prev) {
    try { await prev; } catch { /* previous holder errored */ }
  }

  const current = fn();
  inProcessLocks.set(name, current);

  try {
    return await current;
  } finally {
    if (inProcessLocks.get(name) === current) {
      inProcessLocks.delete(name);
    }
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: processLock,
  }
});
